variables:
  triggeredByPullRequest: $[eq(variables['Build.Reason'], 'PullRequest')]

stages:
  - stage: BuildPublishArtifact
    jobs:
      - job: Manylinux2014Build
        pool:
          vmImage: 'ubuntu-latest'
        container: quay.io/pypa/manylinux2014_x86_64:latest
        strategy:
          matrix:
            linux_py37:
              python.version: 'cp37-cp37m'
            linux_py38:
              python.version: 'cp38-cp38'
            linux_py39:
              python.version: 'cp39-cp39'
            linux_py310:
              python.version: 'cp310-cp310'
        steps:
        - script: |
            "${PYBIN}/python" -m pip install --upgrade pip
            "${PYBIN}/python" -m pip install wheel
            "${PYBIN}/python" -m pip install -r requirements.txt
          displayName: 'Install dependencies and build tools'
          env:
            PYBIN: /opt/python/$(python.version)/bin
        - script: |
            "${PYBIN}/python" setup.py sdist bdist_wheel
          displayName: 'Build wheels'
          env:
            PYBIN: /opt/python/$(python.version)/bin
        - script: |
            auditwheel repair dist/*linux_x86_64.whl --plat manylinux2014_x86_64 -w wheelhouse-manylinux/
          displayName: 'Audit wheels'
        
        - task: DownloadSecureFile@1
          name: PYPIRC_CONFIG
          displayName: 'Download pypirc'
          inputs:
            secureFile: 'pypirc'  
        
        - script: |
            "${PYBIN}/python" -m twine upload -r testpypi --config-file $(PYPIRC_CONFIG.secureFilePath) --skip-existing --disable-progress-bar wheelhouse-manylinux/*
            "${PYBIN}/python" -m twine upload -r testpypi --config-file $(PYPIRC_CONFIG.secureFilePath) --skip-existing --disable-progress-bar dist/*.tar.gz
          displayName: 'Publish wheel to PyPi'
          env:
            PYBIN: /opt/python/$(python.version)/bin
