variables:
  triggeredByPullRequest: $[eq(variables['Build.Reason'], 'PullRequest')]

stages:
  - stage: BuildPublishArtifact
    jobs:
      - job: BuildArtifacts
        displayName: Build source dists and wheels  
        strategy:
          matrix:
            linux_py310:
              imageName: 'ubuntu-latest'
              python.version: '3.10'

        pool:
            vmImage: $(imageName)

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(python.version)'
            displayName: 'Use Python $(python.version)'

          - script: |
              python -m pip install --upgrade pip
              pip install wheel
              pip install -r requirements.txt
              pip install auditwheel
            displayName: 'Install dependencies'

          - script: |
              pip install -e .
            displayName: 'Install package locally'
          
          - script: |
              python setup.py sdist bdist_wheel
            displayName: 'Build package'

          # Upload seperate artifacts for windows and Linux/macOS
          - script: |
              pip install twine
              auditwheel repair dist/*linux_x86_64.whl
            displayName: 'Upload to PyPI - Linux/macOS'
            condition: |
              and
              (
                succeeded(), 
              )
